build_from:
  aarch64: 'ghcr.io/home-assistant/aarch64-base-debian:bullseye'
  amd64: 'ghcr.io/home-assistant/amd64-base-debian:bullseye'
  armhf: 'ghcr.io/home-assistant/armhf-base-debian:bullseye'
  armv7: 'ghcr.io/home-assistant/armv7-base-debian:bullseye'
  i386: 'ghcr.io/home-assistant/i386-base-debian:bullseye'
labels:
  org.opencontainers.image.title: 'Home Assistant Add-on: Xiaomi Mi Flora add-on'
  org.opencontainers.image.description: 'Xiaomi Mi Flora add-on for Home Assistant'
  org.opencontainers.image.source: 'https://github.com/selleronom/xiaomi-mi-flora'
  org.opencontainers.image.licenses: 'Apache License 2.0'
args:
  MIFLORA-MQTT-DAEMON_VERSION: 'master'
